site_name: Cantonres Tutorials
pages:
    - Home: README.md
    - Ingress: ingress/README.md
    - Telegram: telegram/README.md
    - Website: website/README.md

repo_url: https://github.com/ResistanceCN/Tutorials
edit_uri: edit/master/docs/
dev_addr: 0.0.0.0:57836
docs_dir: '/srv/Tutorials/docs/'
theme_dir: '/srv/Tutorials/mkdocs-material-1.8.0/material'

